/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComments {
        /**
          * Public access token to the Supabase backend.
         */
        "supabaseKey": string;
        /**
          * Public URL to the Supabase backend.
         */
        "supabaseUrl": string;
    }
}
declare global {
    interface HTMLMyCommentsElement extends Components.MyComments, HTMLStencilElement {
    }
    var HTMLMyCommentsElement: {
        prototype: HTMLMyCommentsElement;
        new (): HTMLMyCommentsElement;
    };
    interface HTMLElementTagNameMap {
        "my-comments": HTMLMyCommentsElement;
    }
}
declare namespace LocalJSX {
    interface MyComments {
        /**
          * Public access token to the Supabase backend.
         */
        "supabaseKey"?: string;
        /**
          * Public URL to the Supabase backend.
         */
        "supabaseUrl"?: string;
    }
    interface IntrinsicElements {
        "my-comments": MyComments;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-comments": LocalJSX.MyComments & JSXBase.HTMLAttributes<HTMLMyCommentsElement>;
        }
    }
}
